packages:
    - 'apps/*'
    - 'packages/*'

catalog:
    # React ecosystem
    '@tanstack/react-query': ^5.87.1
    '@tanstack/react-query-devtools': ^5.87.1
    '@tanstack/react-table': ^8.21.3
    react: ^19.1.1
    react-dom: ^19.1.1
    react-aria: ^3.42.0
    react-aria-components: ^1.12.2
    react-hook-form: ^7.62.0

    # Next.js ecosystem
    next: ^15.4.5
    next-themes: ^0.4.6

    # Validation & Forms
    zod: ^3.25.76
    '@hookform/resolvers': ^5.2.1

    # UI & Styling
    lucide-react: ^0.475.0
    sonner: ^2.0.7
    tailwindcss: ^4.1.11

    # Development tools
    typescript: ^5.9.2
    eslint: ^9.35.0
    prettier: ^3.6.2

    # Type definitions
    '@types/react': ^19.1.9
    '@types/react-dom': ^19.1.7
    '@types/node': ^20.19.9

catalogs:
    react19:
        '@types/react': ^19.1.9
        '@types/react-dom': ^19.1.7
        react: ^19.1.1
        react-dom: ^19.1.1

nodeLinker: hoisted
linkWorkspacePackages: true
